apiVersion: apps/v1
kind: Deployment
metadata:
  name: okkkk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okkkk
  template:
    metadata:
      labels:
        app: okkkk
    spec:
      containers:
      - image: okteto.dev/okkkk:latest
        name: okkkk
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "48657595-d60b-43fe-ad6c-488a82cfe5dc"
        - name: Vless_Path
          value: "/vlok555"
        - name: Vmess_UUID
          value: "48657595-d60b-43fe-ad6c-488a82cfe5dc"
        - name: Vmess_Path
          value: "/vmok666"
        - name: Share_Path
          value: "/v2link"
